<?php 

namespace ManaPHP\Mvc\Model {

	/**
	 * ManaPHP\Mvc\Model\ValidatorInterface initializer
	 */
	
	interface ValidatorInterface {

		/**
		 * Returns messages generated by the validator
		 *
		 * @return array
		 */
		public function getMessages();


		/**
		 * Executes the validator
		 *
		 * @param \ManaPHP\Mvc\ModelInterface $record
		 * @return boolean
		 */
		public function validate($record);

	}
}
